version: "3.6"
services:
  nginx:
        image: nginx
        container_name: nginx
        working_dir: /nginx-test
        ports:
          - "80:80"
        stdin_open: true
        networks:
          nginx-master:
             ipv4_address: 172.50.0.5
        tty: true
        privileged: true
        volumes:
            - /Docker/nginx/nginx-load:/nginx-test
            - /Docker/nginx/lua-project/nginx-load:/nginx-test/lua-project
            - /Docker/nginx/lua:/lua-packge
        entrypoint:
          - /bin/bash
          - nginx.sh
  nginx-lua1:
        image: nginx
        container_name: nginx-lua1
        working_dir: /nginx-test
        ports:
          - "8002:80"
        stdin_open: true
        networks:
            nginx-slave:
             ipv4_address: 172.30.0.5
        tty: true
        privileged: true
        volumes:
          - /Docker/nginx/nginx-lua1:/nginx-test
          - /Docker/nginx/lua:/lua-packge
          - /Docker/nginx/lua-project/nginx-lua:/nginx-test/lua-project
        entrypoint:
          - /bin/bash
          - nginx.sh

  nginx-lua2:
          image: nginx
          container_name: nginx-lua2
          working_dir: /nginx-test
          ports:
            - "8003:80"
          stdin_open: true
          networks:
             nginx-slave:
               ipv4_address: 172.30.0.6
          tty: true
          privileged: true
          volumes:
              - /Docker/nginx/nginx-lua2:/nginx-test
              - /Docker/nginx/lua:/lua-packge
              - /Docker/nginx/lua-project/nginx-lua:/nginx-test/lua-project
          entrypoint:
            - /bin/bash
            - nginx.sh
networks:
  nginx-master:
      external:
         name: redis_redis-master
  nginx-slave:
      external:
          name: redis_redis-slave